name: PostgreSQL Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute init.sql
        env:
          PGHOST: ${{ secrets.HOST }}
          PGDATABASE: ${{ secrets.DB }}
          PGUSER: ${{ secrets.USER }}
          PGPASSWORD: ${{ secrets.PASSWORD }}
        run: |
          psql -h $PGHOST -U $PGUSER -d $PGDATABASE -p 5432-f scripts/init.sql

      - name: Verify if init.sql was executed successfully
        env:
          PGHOST: ${{ secrets.HOST }}
          PGDATABASE: ${{ secrets.DB }}
          PGUSER: ${{ secrets.USER }}
          PGPASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sleep 5
          psql -h $PGHOST -U $PGUSER -d $PGDATABASE -p 5432 -c "SELECT COUNT(*) FROM egresado_basico;"
