name: PostgreSQL Test

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: harmon758/postgresql-action@v1
       with:
        postgresql version: '15'
        postgresql db: ${{ secrets.DB }}
        postgresql user: ${{ secrets.USER }}
        postgresql password: ${{ secrets.PASSWORD }} 
        postgresql init scripts: /scripts/init.sql
